### ISSUE TITLE
Unable to install plugin

### ISSUE THREAD

**Issue by raymak23** [QueenCityCodeFactory/LDAP#1]
Hello,

I tried to follow installation instruction from github but when I try to download files from composer, I get an error "Could not find package queencitycodefactory/ldap at any version for your minimum-stability (stable)"

Here is the command I tried: php composer.phar require queencitycodefactory/ldap

**Comment by darensipes** [comment]
What version of CakePHP are you using?

**Comment by darensipes** [comment]
We created a 1.0 tag that should solve this issue. Sorry about that. Give it another try and let us know if you have any issues. Thanks!

**Comment by raymak23** [comment]
Hi, thank you for your quick response. I'm using latest cakephp 3.1.5 version. I will give it a try.
