### ISSUE TITLE
LDAP Search attribute

### ISSUE THREAD

**Issue by Nic0tiN** [QueenCityCodeFactory/LDAP#2]
Hello, 

I came across a mini-bug with the search attribute. If I change the search attribute to "sAMAccountName", as the method LdapAuthenticate::_findUser is appending the domain to the username, the filter string fails due to an incorrect username format.

To avoid this, may be you should append the suffix setting to the username in the filter string.

Nic

**Comment by johanvanderkuijl** [comment]
I had the same problem and fixed it by using a closure instead of a fixed search string in the app.php, like this:

``` php
        'search' => function($username, $domain) {
            if (strpos($username, $domain) !== false) {
                // username has @domain in it, remove it.
                $username = str_replace('@' . $domain, '', $username);
            }
            $search = '(&(objectCategory=person)(samaccountname=' . $username. '))';
            return $search;
        }, 
```
