### ISSUE TITLE
Protocol Version

### ISSUE THREAD

**Issue by irongomme** [QueenCityCodeFactory/LDAP#6]
OpenLDAP need LDAP_OPT_PROTOCOL_VERSION defined.

You could just add this to make it works : 

```
ldap_set_option($this->ldapConnection, LDAP_OPT_PROTOCOL_VERSION, 3);
```

**Comment by darensipes** [comment]
@irongomme I have added a way to pass options to the constructor for the LdapAuthenticate class. So you can now pass something like this: 

``` php
'options' => [
        LDAP_OPT_NETWORK_TIMEOUT => 5,
        LDAP_OPT_PROTOCOL_VERSION => 3
],
```

**Comment by irongomme** [comment]
:clap:
