### ISSUE TITLE
Authentication adapter "Ldap.Ldap" was not found. 

### ISSUE THREAD

**Issue by PalantirMHM** [QueenCityCodeFactory/LDAP#7]
Hi there
I'm having this problem that I can't find a way to solve it

`<?php
/**
 * CakePHP(tm) : Rapid Development Framework (http://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 * @link      http://cakephp.org CakePHP(tm) Project
 * @since     0.2.9
 * @license   http://www.opensource.org/licenses/mit-license.php MIT License
 */
namespace App\Controller;

use Cake\Controller\Controller;
use Cake\Event\Event;
use Cake\ORM\TableRegistry;
use Cake\Core\Configure;
use Ldap\Auth\LdapAuthenticate;

/**
 * Application Controller
 *
 * Add your application-wide methods in the class below, your controllers
 * will inherit them.
 *
 * @link http://book.cakephp.org/3.0/en/controllers.html#the-app-controller
 */
class AppController extends Controller
{

    /**
     * Initialization hook method.
     *
     * Use this method to add common initialization code like loading components.
     *
     * e.g. `$this->loadComponent('Security');`
     *
     * @return void
     */
    public function initialize()
    {
        parent::initialize();

        $this->loadComponent('RequestHandler');
        $this->loadComponent('Flash');
        $this->loadComponent('Auth', [
            'loginAction' => [
                'controller' => 'Users',
                'action' => 'login'
            ],
            'authError' => 'Você não tem autorização para acessar esta área!',
            'authenticate' => [
                'Ldap.Ldap' => [
                    'fields' => [
                        'username' => '+++',
                        'password' => '*****'
                    ],
                    'port' => Configure::read('Ldap.port'),
                    'host' => Configure::read('Ldap.host'),
                    'domain' => Configure::read('Ldap.domain'),
                    'baseDN' => Configure::read('Ldap.baseDN'),
                    'bindDN' => Configure::read('Ldap.bindDN'),
                    'search' => Configure::read('Ldap.search'),
                    'errors' => Configure::read('Ldap.errors'),
                    'logErrors' => Configure::read('Ldap.logErrors'),
                    'options' => Configure::read('Ldap.options'),
                    'flash' => [
                        'key' => 'ldap',
                        'element' => 'Flash/error',
                    ]
                ]
            ]
        ]);
    }

    /**
     * Before render callback.
     *
     * @param \Cake\Event\Event $event The beforeRender event.
     * @return \Cake\Network\Response|null|void
     */
    public function beforeRender(Event $event)
    {
        if (!array_key_exists('_serialize', $this->viewVars) &&
            in_array($this->response->type(), ['application/json', 'application/xml'])
        ) {
            $this->set('_serialize', true);
        }

        $departments = TableRegistry::get('Departments');

        $departmentsList = $departments->find('List');
        $this->set(compact('departmentsList'));
    }

    public function isAuthorized($user)
    {
        return true;
    }
}
`
My Configuration is on the end of app.php almost the same way. But I don't think that is the problem here.
I'm using cakephp 3.4, php 7 with the LDAP module on

**Comment by darensipes** [comment]
What if you extend the LdapAuthenticate class like:

```php
namespace App\Auth;

use Cake\Log\LogTrait;
use Ldap\Auth\LdapAuthenticate;

class MyLdapAuthenticate extends LdapAuthenticate
{
    use LogTrait;
```

Then change `Ldap.Ldap` in the app controller to `MyLdap`

The MyLdapAuthenticate class would go in src/Auth/ and be named MyLdapAuthenticate.php.

We extend this class for our application anyways because there is always some application specific code we need to add. If you get us some more details we might be able to figure out why Ldap.Ldap is not working but it is hard to tell without more information.

**Comment by PalantirMHM** [comment]
Thank you for your answer, I did that and received a new error:
```
Error: Class 'Ldap\Auth\LdapAuthenticate' not found
File /var/www/html/radar-tech/src/Auth/SerproLdapAuthenticate.php
Line: 8 
```
Now I downloaded your code via composer, and it is on Vendor\QueenCity.. shouldn't I being including this somewhere? I haven't found anything for that. Sorry if this sound stupid, maybe it is, but it has been ages that I haven't work with cake (1.2)

My composer.json looks like this:

`{
    "name": "cakephp/app",
    "description": "CakePHP skeleton app",
    "homepage": "http://cakephp.org",
    "type": "project",
    "license": "MIT",
    "require": {
        "php": ">=5.5.9",
        "cakephp/cakephp": "3.3.*",
        "mobiledetect/mobiledetectlib": "2.*",
        "cakephp/migrations": "~1.0",
        "cakephp/plugin-installer": "*",
        "friendsofcake/bootstrap-ui": "^0.5.1",
        "queencitycodefactory/ldap": "^3.2"
    },
    "require-dev": {
        "psy/psysh": "@stable",
        "cakephp/debug_kit": "~3.0",
        "cakephp/bake": "~1.1"
    },
    "suggest": {
        "markstory/asset_compress": "An asset compression plugin which provides file concatenation and a flexible filter system for preprocessing and minification.",
        "phpunit/phpunit": "Allows automated tests to be run without system-wide install.",
        "cakephp/cakephp-codesniffer": "Allows to check the code against the coding standards used in CakePHP."
    },
    "autoload": {
        "psr-4": {
            "App\\": "src"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Test\\": "tests",
            "Cake\\Test\\": "./vendor/cakephp/cakephp/tests"
        }
    },
    "scripts": {
        "post-install-cmd": "App\\Console\\Installer::postInstall",
        "post-create-project-cmd": "App\\Console\\Installer::postInstall",
        "post-autoload-dump": "Cake\\Composer\\Installer\\PluginInstaller::postAutoloadDump",
        "check": [
            "@cs-check",
            "@test"
        ],
        "cs-check": "vendor/bin/phpcs --colors -p --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests",
        "cs-fix": "vendor/bin/phpcbf --colors --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests",
        "test": "vendor/bin/phpunit --colors=always"
    },
    "minimum-stability": "beta",
    "prefer-stable": true,
    "config":{
      "vendor-dir": "Vendor"
   }
}`

**Comment by darensipes** [comment]
What is the path to the plugin in the vendor directory? I would expect /var/www/html/radar-tech/vendor/queencitycodefactory/ldap/

What does this file (/var/www/html/radar-tech/src/Auth/SerproLdapAuthenticate.php) look like?

**Comment by darensipes** [comment]
Ldap\Auth\LdapAuthenticate is not found, try `composer update`

**Comment by darensipes** [comment]
I have a file cakephp-plugins.php in my vendor directory that has `'Ldap' => $baseDir . '/vendor/queencitycodefactory/ldap/',` as one of the plugins. Do you have this?

**Comment by PalantirMHM** [comment]
Ok I'll answer in order:

1) SerproLdapAuthenticate.php only calls LdapAuthenticate.php now, having nothing but the code you showed me.

2) I did, by the way I changed the version from "^3.2" to "queencitycodefactory/ldap" : "dev-master"

3) I have that, but I have two folders: a Vendor (where you code is) and a vendor

**Comment by PalantirMHM** [comment]
Ok I found out: it's the Vendor/vendor problem
My bootstrap.php file only loaded the vendor plugins, I add
`require __DIR__ . '/../Vendor/autoload.php';`

And now I'm good to go, thanks.
