### ISSUE TITLE
Would you like to contribute LDAP to the new CakePHP Authentication?

### ISSUE THREAD

**Issue by burzum** [QueenCityCodeFactory/LDAP#8]
Hello, we've discussed including LDAP in the new CakePHP authentication system and it looks like your plugin would be super easy to convert. We just don't have anyone yet who is using LDAP so we don't have an LDAP server either set up.

If you're interested please check the authentication plugin https://github.com/cakephp/authentication/issues/86

**Comment by dereuromark** [comment]
Once you have some Basic Tests please also consider submitting to https://github.com/FriendsOfCake/awesome-cakephp#authentication-and-authorization

**Comment by darensipes** [comment]
Sure, we are interested. I have to think about how to write the test since there won't be an LDAP sever to bind. Maybe the test can hit an open source LDAP server or maybe we can figure out a way to simulate or run a local LDAP server on PHP.

**Comment by burzum** [comment]
@darensipes we are already almost done with an LDAP implementation. :)

https://github.com/cakephp/authentication/pull/109
